### ISSUE TITLE
latest ci deployment fails

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#462]
# Tasks to improve tests on the branch (no PR)
- [x] Fix Test on development
- [x] #488
  - [ ] restart cluster to fix stuck PVC an other state problems
  - [ ] docker demon restart
- [x] #500
